### PR TITLE
Updates for 0.6

### PR DESCRIPTION
**Pull request by ararslan**
This PR adds some compatibility updates for Julia 0.6, drops support for Julia 0.3, enables precompilation, enhances the README, and updates the Travis YAML.

### CODE REVIEW

**Comment by tknopp** [comment]
Thanks @ararslan!

**Comment by ararslan** [comment]
My pleasure! If you could tag a release to avoid the deprecation warnings on 0.6, that would be fantastic. (Note that it will have to be a minor release since support for Julia 0.3 has been dropped.)

**Comment by tknopp** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8299

**Comment by ararslan** [comment]
Wonderful, thanks. And thanks for the organization invitation. 🙂

**Comment by tknopp** [comment]
Well according to https://github.com/JuliaIO/IniFile.jl/graphs/contributors your are now the maintainer of this package. Merge rights would be helpful for this job ;-)  (just kidding)

**Comment by tknopp** [comment]
I think this is a good example how it can be really helpful to group packages into organizations where everybody tries to have a look at different packages. As you see IniFile is basically maintainerless. But still its being used (e.g. by me) and in turn needs maintenance from time to time.

**Pull request merged**
